name: Tests
on: [push, pull_request]

jobs:
  tests:
    env:
      FORCE_COLOR: "1"
      PRE_COMMIT_COLOR: "always"

    strategy:
      fail-fast: false

    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up environment"
        run: docker compose up -d --build

      - name: "Wait for docker to finish building"
        run: sleep 30

      - name: "Run tests"
        run: docker compose exec django_test nox -r --force-color

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs/_build

      - name: Combine coverage data and display human readable report
        run: |
          docker compose exec django_test nox --session "coverage(django='4.2')"

      - name: Create coverage report
        run: |
          docker compose exec django_test nox --session "coverage(django='4.2')" -- xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3.1.4
